# Generated by Django 3.2 on 2022-06-16 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DessertComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('dessert', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thai.dessert')),
            ],
        ),
    ]
