# Generated by Django 3.2 on 2022-06-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thai', '0003_auto_20220626_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='dessertcomment',
            old_name='body',
            new_name='comment',
        ),
    ]
