# Generated by Django 3.2 on 2022-06-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thai', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
