# Generated by Django 3.2 on 2022-04-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thai', '0003_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Index',
        ),
    ]
