# Generated by Django 3.2 on 2022-04-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thai', '0004_rename_home_index'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='Home',
        ),
    ]
