# Generated by Django 3.2 on 2022-05-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thai', '0004_auto_20220526_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ManyToManyField(related_name='item', to='thai.Category'),
        ),
    ]
