# Generated by Django 3.2 on 2022-06-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thai', '0007_auto_20220526_1145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Success',
        ),
    ]
