# Generated by Django 3.2 on 2022-06-11 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thai', '0008_delete_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='likes',
            field=models.ManyToManyField(related_name='Dessert_Likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meal',
            name='likes',
            field=models.ManyToManyField(related_name='Meal_Likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
