# Generated by Django 3.2 on 2022-06-11 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thai', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Dessert_Likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
