# Generated by Django 3.2 on 2022-06-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thai', '0012_auto_20220611_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_on',
        ),
    ]
