# Generated by Django 3.2 on 2022-06-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thai', '0013_auto_20220611_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='title',
        ),
    ]
