# Generated by Django 3.2 on 2022-06-11 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thai', '0014_rename_name_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='Dessert_Comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meal',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='Meal_Comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
