# Generated by Django 3.2 on 2022-06-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thai', '0015_auto_20220611_1322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
