# Generated by Django 3.2 on 2022-06-12 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thai', '0016_auto_20220612_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thai.meal'),
        ),
    ]
