# Generated by Django 3.2 on 2022-06-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thai', '0017_comment_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dessert',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='likes',
        ),
    ]
